import { Geist, Geist_Mono } from "next/font/google";
 import "./globals.css";
import NavBAr from "./components/navbar";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
    const resolvedParams = await params;
  if (!hasLocale(routing.locales, resolvedParams.locale)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html 
    lang={resolvedParams}
      dir={resolvedParams.locale === "ar" ? "rtl" : "ltr"}
      >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider
        locale={resolvedParams.locale}
        messages={messages}
        >
        <NavBAr />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
